cpc_video_game:
    resource: "@CPCVideoGameBundle/Resources/config/routing.yml"
    prefix:   /

cpc_ranking:
    resource: "@CPCRankingBundle/Resources/config/routing.yml"
    prefix:   /

cpc_game:
    resource: "@CPCGameBundle/Resources/config/routing.yml"
    prefix:   /

cpc_player:
    resource: "@CPCPlayerBundle/Resources/config/routing.yml"
    prefix:   /

cpc_team:
    resource: "@CPCTeamBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"