services:
    cpc_video_game_twig_video_game_helper.example:
        class     : CPC\VideoGameBundle\Twig\VideoGameHelper
        public    : false
        tags      :
            - { name: twig.extension }
        arguments :    ['@doctrine.orm.entity_manager']
