<?php

namespace CPC\GameBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOrdered($id)
	{
        $qb = $this->createQueryBuilder('g')
        	->where('g.team1 = :id')
		    ->orWhere('g.team2 = :id')
		    ->setParameter('id', $id)
            ->OrderBy('g.id', 'DESC');
        $query = $qb->getQuery();
        //Debug
        //var_dump($query->getDQL());die;
        return $query->execute();
	}
}
